[tool.poetry]
name = "can-explorer"
version = "0.1.0"
description = "Visualize CAN bus payloads in real time"
authors = ["TJ <tbruno25@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8, <4.0"
pyserial = "^3.5"
python-can = "^4.1.0"
dearpygui = "^1.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
mypy = "^1.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[tool.poetry.scripts]
can-explorer = "can_explorer.app:main"