name: CI

on:
  pull_request:
  push:
    branches:
      - 'ci/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0

  validate:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test linux
      if: runner.os != 'Windows'
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          sudo apt-get install -y xvfb xserver-xephyr scrot
          python -m pip install poetry
          poetry install -v
          mkdir -p screenshots
          xvfb-run -a poetry run pytest -v

    - name: Test windows
      if: runner.os == 'Windows'
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: |
          python -m pip install poetry==1.3.1
          poetry install -v
          mkdir -p screenshots
          poetry run pytest -v

    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: screenshots/*.png
        
    - name: Typecheck
      run: poetry run mypy src
